export const DOCUMENT_ACCESS_ROLES = [
  'ADMIN',
  'DIRECTOR',
  'DEPARTMENT_HEAD',
  'MANAGER',
  'LOGIST',
  'FINANCIER',
];

export const DOCUMENT_DOWNLOAD_ROLES = {
  CONTRACT: ['ADMIN', 'DIRECTOR', 'DEPARTMENT_HEAD', 'MANAGER'],
  CONTRACT_WITHOUT_DEAL: [
    'ADMIN',
    'DIRECTOR',
    'DEPARTMENT_HEAD',
    'MANAGER',
    'LOGIST',
  ],
  TRANSPORT_REQUEST: [
    'ADMIN',
    'DIRECTOR',
    'DEPARTMENT_HEAD',
    'MANAGER',
    'LOGIST',
  ],
  INVOICE: ['ADMIN', 'DIRECTOR', 'DEPARTMENT_HEAD', 'MANAGER', 'FINANCIER'],
} as const;
